# 设置端⼝为8080
server:
  port: 8080
spring:
  data:
  mongodb:
  authentication-database: admin
  database: demo
  username: root
  password: "123456" #注意这⾥要⽤引号把密码括起来
  host: 127.0.0.1
  port: 27017